version: 2.1
orbs:
  browser-tools: circleci/browser-tools@1.4.8
jobs:
  build:
    working_directory: ~/sunbird-collection-editor
    docker:
    - image: cimg/node:18.19.1-browsers
    steps:
      - browser-tools/install-chrome
      - run:
          command: google-chrome --version
      - checkout:
          path: ~/sunbird-collection-editor
      - run:
          name: Node version
          command: 'node --version'
      - run:
          name: Installing angular cli
          command: 'npm install -g @angular/cli@16 --no-progress'
      #~ - restore_cache:
          #~ key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Installing npm deps
          command: 'npm install --no-progress'
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths: ./node_modules
      - run:
          name: ng lint and building
          command: 'mkdir -p /tmp/logs && npm run build-lib:prod | tee /tmp/logs/build.log'
      - run:
          name: Executing test cases
          command: 'npm run test-coverage | tee /tmp/logs/test_cases.log'
      - run:
          name: Install sonar scanner
          command: npm install -g sonarqube-scanner
      - run:
          name: Run sonar scanner
          command: 'cd ~/sunbird-collection-editor && sonar-scanner'
      # - run:
      #     name: Publish web component to NPM
      #     command: |
      #       if [ -z $CIRCLE_PR_NUMBER ]; then
      #         npm run build-web-component && npm pack ./web-component
      #         echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
      #         npm publish project-sunbird-sunbird-collection-editor-web-component-* --access=public
      #       else
      #         npm run build-web-component && npm pack ./web-component
      #       fi
      - run:
          name: Publish to NPM
          command: |
            if [ -z $CIRCLE_PR_NUMBER ]; then
              npm run build-lib && npm pack ./dist/collection-editor-library
              npm publish project-sunbird-sunbird-collection-editor-* --access=public
            else
              npm run build-lib && npm pack ./dist/collection-editor-library
            fi
workflows:
  version: 2.1
  build_and_test:
    jobs:
      - build
